const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const json = file => JSON.parse(read(file));
const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};

const html = read("index.html");
const style = read("style.css");
const engine = read("engine.js");
const app = read("app.js");
const copyBank = read("qimen_soul_copy_bank.js");
const manifest = json("manifest.webmanifest");
const lock = json("rules/lock-palace.json");
const scoring = json("rules/scoring.json");
const qtype = json("rules/qtype-rules.json");
const index = json("rules/rules.json");

assert(html.includes("style.css"), "index.html must load style.css");
assert(html.includes("engine.js"), "index.html must load engine.js");
assert(html.includes("app.js"), "index.html must load app.js");
assert(html.includes("qimen_soul_copy_bank.js"), "index.html must load the soul copy bank");
assert(html.includes("manifest.webmanifest"), "index.html must load the manifest");
assert(html.includes("caseList"), "case library UI is missing");
assert(html.includes("metricRules"), "rule version display is missing");
assert(html.includes("九宮奇門"), "app name should be 九宮奇門");
assert(html.includes("簡略報告"), "simple report button is missing");
assert(html.includes("詳細報告"), "detail report button is missing");
assert(html.includes("老師教學"), "teacher report button is missing");
assert(html.includes("selectionMode"), "selection mode control is missing");
assert(html.includes("comparePanel"), "compare mode panel is missing");
assert(html.includes("questionDiagnosis"), "question diagnosis panel is missing");
assert(html.includes("applyDiagnosisQtype"), "apply diagnosis qtype button is missing");
assert(html.includes("applyQuestionRewrite"), "apply question rewrite button is missing");
assert(html.includes("applyDecisionOptions"), "apply decision option drafts button is missing");
assert(html.includes("optionAName") && html.includes("optionBName") && html.includes("optionCName") && html.includes("optionDName"), "compare option fields are missing");
assert(html.includes("caseAfterAction"), "after-action feedback field is missing");
assert(html.includes("caseVerifiedSymbol"), "verified symbol feedback field is missing");
assert(html.includes("caseRiskReduced"), "risk reduction feedback field is missing");
assert(html.includes("caseDeviationResult"), "deviation result feedback field is missing");
assert(html.includes("caseCalibration"), "case calibration feedback field is missing");
assert(html.includes("caseCompareChosen"), "compare chosen feedback field is missing");
assert(html.includes("caseCompareHit"), "compare hit feedback field is missing");
assert(html.includes("caseCompareNote"), "compare note feedback field is missing");
assert(html.includes("caseReviewFilter"), "case review quality filter is missing");
assert(html.includes("priority"), "priority review filter is missing");
assert(html.includes("low-accuracy"), "low-accuracy review filter is missing");
assert(html.includes("compare-incomplete"), "compare incomplete review filter is missing");
assert(html.includes("compare-chosen-mismatch"), "compare chosen mismatch review filter is missing");
assert(html.includes("compare-hit-mismatch"), "compare hit mismatch review filter is missing");
assert(html.includes("copyCaseReviewChecklist"), "case review checklist copy button is missing");
assert(html.includes("copyFilteredCaseReviewChecklist"), "filtered case review checklist copy button is missing");
assert(html.includes("copyCaseCalibrationSummary"), "case calibration summary copy button is missing");
assert(html.includes("exportCasesCsv"), "case review CSV export button is missing");
assert(html.includes("exportFilteredCasesCsv"), "filtered case review CSV export button is missing");
assert(html.includes("caseStats"), "case calibration stats panel is missing");
assert(html.includes("info-fold"), "collapsible information sections are missing");
assert(html.includes("?v=5.0-decision-29"), "cache-busting version should be updated for V5.0 decision build");
assert(!html.includes("5 改取 2"), "user-facing 5-to-2 wording should stay hidden");
assert(!html.includes("太虛"), "app UI should not mention 太虛");

assert(app.includes("CASE_STORAGE_KEY"), "case storage logic is missing");
assert(app.includes("importJsonFile"), "JSON import logic is missing");
assert(app.includes("registerServiceWorker"), "service worker registration is missing");
assert(app.includes("RULE_VERSION"), "rule version constant is missing");
assert(app.includes("generateSoulReport"), "copy-bank report generator is missing");
assert(app.includes("簡略報告"), "simple report article is missing");
assert(app.includes("詳細報告"), "detail report article is missing");
assert(app.includes("老師教學"), "teacher report article is missing");
assert(app.includes("buildCompareContext"), "compare report context builder is missing");
assert(app.includes("formatCompareReport"), "compare report formatter is missing");
assert(app.includes("compareSelections"), "compare selections state is missing");
assert(app.includes("COMPARE_SIDES"), "multi-option comparison sides are missing");
assert(app.includes("decisionMetricsForChoice"), "decision option metrics are missing");
assert(app.includes("decisionOptions"), "case records should store decision options");
assert(app.includes("decisionCards"), "case records should store decision cards");
assert(app.includes("scorePalaceV5"), "V5 scoring function is missing");
assert(app.includes("diagnoseQuestion"), "question diagnosis function is missing");
assert(app.includes("buildQuestionRewrite"), "question rewrite helper is missing");
assert(app.includes("applyQuestionRewrite"), "question rewrite apply handler is missing");
assert(app.includes("suggestDecisionOptions"), "decision option draft helper is missing");
assert(app.includes("applyDecisionOptionDrafts"), "decision option draft apply handler is missing");
assert(app.includes("problemDiagnosis"), "problem diagnosis should be stored with charts/cases");
assert(app.includes("buildRiskProfile"), "risk profile builder is missing");
assert(app.includes("riskProfileText"), "risk profile report text is missing");
assert(app.includes("analyzeThreePalaces"), "three-palace analysis is missing");
assert(app.includes("findPalacesBySymbol"), "symbol palace lookup is missing");
assert(app.includes("palaceRelation"), "palace relation helper is missing");
assert(app.includes("reportHTML"), "structured report renderer is missing");
assert(app.includes("afterAction"), "case after-action feedback is missing");
assert(app.includes("verifiedSymbol"), "case verified symbol feedback is missing");
assert(app.includes("riskReduced"), "case risk reduction feedback is missing");
assert(app.includes("compareChosen"), "case compare chosen feedback is missing");
assert(app.includes("compareHit"), "case compare hit feedback is missing");
assert(app.includes("compareOptionLabel"), "case compare option label helper is missing");
assert(app.includes("compareMatchLabel"), "case compare match label helper is missing");
assert(app.includes("compareChosenMismatch"), "case compare chosen mismatch helper is missing");
assert(app.includes("compareHitMismatch"), "case compare hit mismatch helper is missing");
assert(app.includes("compareHitMatchRate"), "case compare recommendation hit-rate is missing");
assert(app.includes("deviationResult"), "case deviation result feedback is missing");
assert(app.includes("calibration"), "case calibration feedback is missing");
assert(app.includes("riskReducedLabel"), "risk reduction label helper is missing");
assert(app.includes("calibrationLabel"), "calibration label helper is missing");
assert(app.includes("caseMilestone"), "100-case milestone helper is missing");
assert(app.includes("caseProgressHTML"), "100-case progress renderer is missing");
assert(app.includes("caseTrainingTask"), "case training task helper is missing");
assert(app.includes("caseTrainingTaskHTML"), "case training task renderer is missing");
assert(app.includes("caseCompletion"), "case completion helper is missing");
assert(app.includes("caseMatchesReviewFilter"), "case review filter helper is missing");
assert(app.includes("caseReviewPriority"), "case review priority helper is missing");
assert(app.includes("sortCasesForReview"), "case review priority sort helper is missing");
assert(app.includes("buildCaseReviewChecklist"), "case review checklist builder is missing");
assert(app.includes("copyActiveCaseReviewChecklist"), "case review checklist copy handler is missing");
assert(app.includes("buildFilteredCaseReviewChecklist"), "filtered case review checklist builder is missing");
assert(app.includes("copyFilteredCaseReviewChecklist"), "filtered case review checklist copy handler is missing");
assert(app.includes("filteredReviewCases"), "filtered case review helper is missing");
assert(app.includes("casesToReviewCsv"), "case review CSV exporter is missing");
assert(app.includes("exportFilteredCasesCsv"), "filtered case review CSV exporter is missing");
assert(app.includes("csvCell"), "CSV cell escaping helper is missing");
assert(app.includes("caseStatsFromCases"), "case stats aggregation is missing");
assert(app.includes("calibrationReadinessLabel"), "calibration readiness label helper is missing");
assert(app.includes("readinessPercent"), "case readiness percent is missing");
assert(app.includes("symbolHitKey"), "symbol-hit cross-analysis helper is missing");
assert(app.includes("bySymbolHitArea"), "symbol-hit cross-analysis stats are missing");
assert(app.includes("actionFollowedLabel"), "action-followed classifier is missing");
assert(app.includes("byActionEffect"), "action effectiveness stats are missing");
assert(app.includes("bucketSummary"), "case bucket summary formatter is missing");
assert(app.includes("buildCaseCalibrationSummary"), "case calibration summary builder is missing");
assert(app.includes("copyCaseCalibrationSummary"), "case calibration summary copy handler is missing");
assert(app.includes("calibrationAdvice"), "case calibration advice helper is missing");
assert(app.includes("renderCaseStats"), "case stats renderer is missing");
assert(app.includes("calibrationHints"), "case calibration hints are missing");
assert(app.includes("testCaseStatsAggregation"), "case stats dev test is missing");
assert(app.includes("testCalibrationReadiness"), "calibration readiness dev test is missing");
assert(app.includes("testMilestoneUsesFeedbackCount"), "feedback-based milestone dev test is missing");
assert(app.includes("testCaseCompletionMissingFields"), "case completion dev test is missing");
assert(app.includes("testCompareCaseCompletionFields"), "compare case completion dev test is missing");
assert(app.includes("testCompareRecommendationMatchStats"), "compare recommendation match dev test is missing");
assert(app.includes("testCaseReviewFilter"), "case review filter dev test is missing");
assert(app.includes("testCaseReviewChecklist"), "case review checklist dev test is missing");
assert(app.includes("testCaseReviewCsv"), "case review CSV dev test is missing");
assert(app.includes("testCaseTrainingTask"), "case training task dev test is missing");
assert(app.includes("testCaseCalibrationSummary"), "case calibration summary dev test is missing");
assert(app.includes("testQuestionRewrite"), "question rewrite dev test is missing");
assert(app.includes("testDecisionOptionDrafts"), "decision option draft dev test is missing");
assert(app.includes("decisionOptionStyle"), "compare option style classifier is missing");
assert(app.includes("compareDecisionCard"), "compare decision card helper is missing");
assert(app.includes("testCompareOptionTextsDiffer"), "compare option text differentiation dev test is missing");
assert(app.includes("testCompareDecisionCardFields"), "compare decision card dev test is missing");
assert(app.includes("reportSectionClass"), "report section layout classifier is missing");
assert(!app.includes("大家好，我是太虛"), "report should not mention 太虛 as a persona");
assert(style.includes(".report-section"), "structured report section styles are missing");
assert(style.includes(".report-list"), "report list styles are missing");
assert(style.includes(".report-highlight"), "report highlight styles are missing");
assert(style.includes(".decision-card"), "decision card styles are missing");
assert(style.includes(".case-stats"), "case stats styles are missing");
assert(style.includes(".case-progress"), "100-case progress styles are missing");
assert(style.includes(".case-next-task"), "case next task styles are missing");
assert(style.includes(".case-completion"), "case completion styles are missing");
assert(copyBank.includes("window.QIMEN_COPY_BANK"), "copy bank must expose window.QIMEN_COPY_BANK");
assert(engine.includes("QIMEN_RULE_VERSION"), "engine.js must expose rule version");
assert(engine.includes("QIMEN_RULE_FILES"), "engine.js must expose rule file index");

assert(lock.version === "lock-palace.v5.0", "lock rule version mismatch");
assert(lock.mapping["5"] === 2, "lock mapping for 5 should remain internal 2");
assert(scoring.version === "scoring.v5.0", "scoring version mismatch");
assert(scoring.severity.pending.includes("空"), "empty palace should be pending in V5");
assert(scoring.score.door["開門"] === 40, "score rule for 開門 changed unexpectedly");
assert(qtype.status === "待校準", "qtype rules must remain marked pending calibration");
assert(qtype.types["工作"].applyWeight === true, "qtype weights should be active in V5");
assert(index.files.includes("scoring.json"), "rules index must include scoring.json");
assert(manifest.display === "standalone", "manifest display should be standalone");
assert(manifest.name === "九宮奇門", "manifest app name should be 九宮奇門");

console.log("V5.0 static checks passed.");
